freetype/freetype2-testing

.travis.yml
- Logging should always be compiled out from regression tests.
=> Remove the `glog' package from Travis CI

fuzzing/src/iterators/faceprepiterator-multiplemasters.cpp, fuzzing/src/iterators/faceprepiterator-multiplemasters.h, fuzzing/src/visitors/facevisitor-charcodes.cpp, fuzzing/src/visitors/facevisitor-charcodes.h, fuzzing/src/visitors/facevisitor-gasp.cpp, fuzzing/src/visitors/facevisitor-multiplemasters.cpp, fuzzing/src/visitors/facevisitor-multiplemasters.h, fuzzing/src/visitors/facevisitor-sfntnames.cpp, fuzzing/src/visitors/facevisitor-truetypetables.cpp, fuzzing/src/visitors/facevisitor-truetypetables.h, fuzzing/src/visitors/facevisitor-variants.cpp, fuzzing/src/visitors/facevisitor-variants.h
- Make sure every loop as a reasonable upper bound.
- Values that are printed in `hex` should be prefixed with `0x`.
=> Cleanup the visitors and iterators

fuzzing/README.md, fuzzing/src/targets/CMakeLists.txt, fuzzing/src/targets/font-drivers/cff-render.cpp, fuzzing/src/targets/font-drivers/cidtype1-render.cpp, fuzzing/src/targets/font-drivers/truetype-render.cpp, fuzzing/src/targets/font-drivers/type1-render-base.cpp, fuzzing/src/visitors/facevisitor-autohinter.cpp, fuzzing/src/visitors/facevisitor-autohinter.h, fuzzing/src/visitors/facevisitor-charcodes.cpp, fuzzing/src/visitors/facevisitor-loadglyphs.cpp
- Add `FaceVisitorAutohinter` to fuzz `warping` of `autofitter`.
- Fix a bug in `FaceVisitorCharCodes`: `WARN_ABOUT_IGNORED_VALUES` failed when compiled with a logger.
- Fix order of includes and CMake lists.
=> Fuzz `warping` property of the `autofitter` module + small fixes

fuzzing/scripts/build-freetype.sh, fuzzing/scripts/build-libarchive.sh, fuzzing/src/driver/driver.cpp
- Only clone the part of `freetype2` and `libarchive` that are necessary.
- Remove unnecessary double linebreaks in the usage message of `driver`.
=> Some fixes:

fuzzing/src/visitors/facevisitor-type1tables.cpp, fuzzing/src/visitors/facevisitor-type1tables.h
- `FT_Get_PS_Font_Value` does not touch the value in case of an error.
=> Fix use of `uninitialised value`:

fuzzing/src/visitors/facevisitor-loadglyphs.cpp, fuzzing/src/visitors/facevisitor-loadglyphs.h
- Don't render bitmaps that are larger than 32767 x 32767.
- Only render 33.3% of the glyphs per target.
=> Counteract timeout and out-of-memory issues of OSS-Fuzz

.travis.yml, fuzzing/scripts/README.md, fuzzing/scripts/build-fuzzers.sh, fuzzing/scripts/build/freetype.sh, fuzzing/scripts/build/glog.sh, fuzzing/scripts/build/libarchive.sh, fuzzing/scripts/build/targets.sh, fuzzing/scripts/custom-build.sh, fuzzing/scripts/prepare-oss-fuzz.sh, fuzzing/scripts/travis-ci/oss-fuzz-build.sh, fuzzing/scripts/travis-ci/regression-suite.sh
- Add the OSS-Fuzz row to Travis CI.
- New logic for accessing the scripts' directories.
- Restructure the `/fuzzing/scripts` folder.
=> Add a row to Travis CI to build OSS-Fuzz

.gitmodules, fuzzing/scripts/custom-build.sh
- Due to an attack of Savannah.
- Fix a path in `custom-build.sh' on the fly.
=> Use git protocol for checking out FreeType:

fuzzing/src/iterators/faceloaditerator.cpp, fuzzing/src/iterators/faceprepiterator-bitmaps.cpp, fuzzing/src/iterators/faceprepiterator-multiplemasters.cpp, fuzzing/src/iterators/faceprepiterator-outlines.cpp, fuzzing/src/iterators/glyphloaditerator-naive.cpp, fuzzing/src/iterators/glyphrenderiterator-allmodes.cpp, fuzzing/src/targets/base.cpp, fuzzing/src/utils/faceloader.cpp, fuzzing/src/utils/logging.h, fuzzing/src/utils/utils.cpp, fuzzing/src/visitors/facevisitor-autohinter.cpp, fuzzing/src/visitors/facevisitor-bdf.cpp, fuzzing/src/visitors/facevisitor-charcodes.cpp, fuzzing/src/visitors/facevisitor-cid.cpp, fuzzing/src/visitors/facevisitor-kerning.cpp, fuzzing/src/visitors/facevisitor-loadglyphs.cpp, fuzzing/src/visitors/facevisitor-multiplemasters.cpp, fuzzing/src/visitors/facevisitor-renderglyphs.cpp, fuzzing/src/visitors/facevisitor-sfntnames.cpp, fuzzing/src/visitors/facevisitor-subglyphs.cpp, fuzzing/src/visitors/facevisitor-trackkerning.cpp, fuzzing/src/visitors/facevisitor-truetypetables.cpp, fuzzing/src/visitors/facevisitor-type1tables.cpp, fuzzing/src/visitors/facevisitor-windowsfnt.cpp, fuzzing/src/visitors/glyphvisitor-bitmap-handling.cpp, fuzzing/src/visitors/glyphvisitor-outlines.cpp, fuzzing/src/visitors/glyphvisitor-transform.cpp
- Additionally: reformat some code slightly.
=> Use `LOG_FT_ERROR` to log all FreeType errors properly.

fuzzing/src/utils/utils.cpp
- Restrict the height of rendered glyphs to 5000 pixels.
=> Fix a lot of timeout issues with OSS-Fuzz:

fuzzing/src/iterators/faceloaditerator.cpp, fuzzing/src/iterators/faceloaditerator.h, fuzzing/src/targets/CMakeLists.txt, fuzzing/src/targets/FaceFuzzTarget.cpp, fuzzing/src/targets/FaceFuzzTarget.h, fuzzing/src/utils/faceloader.cpp, fuzzing/src/utils/faceloader.h, fuzzing/src/utils/utils.h
Redefine std::unique_ptr helper Unique_Archive based on forward
declaration, define HAVE_ARCHIVE in CMakeLists.txt and use it
for conditional compilation of tar related setters.
=> Define HAVE_ARCHIVE to allow building without libarchive

fuzzing/src/visitors/facevisitor-multiplemasters.cpp, fuzzing/src/visitors/facevisitor-type1tables.cpp, fuzzing/src/visitors/facevisitor-type1tables.h
In the Chromium build, clang complains about num_subrs being
uninitialized. Fix this to avoid the compiler erroring out on this
variable. In addition, use explict types in a few place to avoid
signed/unsigned comparison issues.
=> Fix unitialized value num_subrs and sign comparison issues

fuzzing/src/visitors/facevisitor-variants.cpp, fuzzing/src/visitors/glyphvisitor-bitmap-handling.cpp, fuzzing/src/visitors/glyphvisitor-transform.cpp
Remove a couple of unused FT_Errors, those showed up
when building as part of Chromium and would currently
require error suppression for a successful build.
=> Fix unused variable build warnings/errors

fuzzing/src/targets/font-drivers/type1-render.cpp, fuzzing/src/targets/font-drivers/type1.cpp
Needed for building the CID and CIDType1 fuzzers
as part of Chromium fuzzing.
=> Build fix when HAVE_ARCHIVE not available

fuzzing/scripts/prepare-oss-fuzz.sh
Hopefully addresses no coverage being reported for the colrv1 fuzzer so
far in oss-fuzz.
=> Include colrv1 in script preparing fuzzer corpora

fuzzing/src/visitors/facevisitor-colrv1.cpp
This is done on the application side, as FreeType would otherwise need
to be aware of traversals, which would carry too much state for how the
API is designed. Documentation in FreeType will be updated accordingly.
Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=33499.
=> Track visited FT_OpaquePaint in order to avoid cycles

fuzzing/src/visitors/facevisitor-colrv1.cpp
The ftcolor.h header needs to be explicitly included and the
experimental COLRv1 support calls have replaced 'transformed' with
'transform'. Update these to fix the build.
=> Include ftcolor.h, s/transformed/transform/g

fuzzing/src/visitors/facevisitor-colrv1.cpp
FT_COLR_PAINTFORMAT_SCALE was recently added to the specification and
upstream FreeType. Add it to the colrv1 visitor.
=> Add FT_COLR_PAINTFORMAT_SCALE

fuzzing/src/visitors/facevisitor-colrv1.cpp
When starting to traverse a glyph, execute retrieval of ClipBox.
Fixes https://gitlab.freedesktop.org/freetype/freetype/-/issues/1083
=> [COLRv1] Add fuzzing for FT_Get_Color_Glyph_ClipBox.

fuzzing/scripts/custom-build.sh
This allows the bdf fuzzer to immediately find the issue reported at
https://lists.nongnu.org/archive/html/freetype-devel/2021-12/msg00001.html
Add this build option first to get local testing and clean up before
proposing adding the MemorySanitizer option to oss-fuzz.
=> Add MemorySanitizer build option.

fuzzing/scripts/build/0001-Add-trace-pc-guard-to-fno-sanitize-coverage.patch, fuzzing/scripts/build/libcxx.sh
This allows building libcxx and libcxxabi with the HonggFuzz fuzzer
which requires sanitize-coverage.
[0] https://github.com/google/oss-fuzz/pull/7033
=> Add trace-pc-guard to no-sanitize-coverage.

fuzzing/scripts/build/libcxx.sh
Properly quote variable expansions for command line arguments. Fixes
builds with spaces in paths and when using ccache as the compiler.
=> Add missing quotes to libcxx.sh

fuzzing/scripts/build/libcxx.sh, fuzzing/scripts/custom-build.sh
AddressSanitizer, MemorySanitizer, and ThreadSanitizer are all mutually
exclusive. The list of incompatible fuzzers can be found at
clang/lib/Driver/SanitizerArgs.cpp in IncompatibleGroups. Modify
custom-build.sh so that only one of these can be picked.
=> Choose exactly one of the exclusive fuzzers

fuzzing/scripts/build/0001-Add-trace-pc-guard-to-fno-sanitize-coverage.patch
Use '-fsanitize-coverage=0' to disable all sanitize-coverage options.
This is undocumented but tested by clang.
=> Use sanitize-coverage=0 not no-sanitize-coverage

fuzzing/scripts/build-fuzzers.sh, fuzzing/scripts/build/bzip2.sh, fuzzing/scripts/build/freetype.sh, fuzzing/scripts/build/libarchive.sh, fuzzing/scripts/build/libpng.sh, fuzzing/scripts/build/zlib.sh, fuzzing/scripts/custom-build.sh
Add missing submodules and consistently check for the existence of build
files and build in the correct directory.
=> Make --rebuild work correctly again.

fuzzing/scripts/build/brotli.sh, fuzzing/scripts/build/bzip2.sh, fuzzing/scripts/build/glog.sh, fuzzing/scripts/build/libarchive.sh, fuzzing/scripts/build/libpng.sh, fuzzing/scripts/build/zlib.sh
The oss-fuzz project recently updated their base image from Ubuntu 16.04
to Ubuntu 20.04, so there should no longer be any need to support git <
2.25. This means that submodules should now be better behaved.
=> Drop support for git <= 2.14.

fuzzing/scripts/build/libcxx.sh
The environment variable CC and CXX are not compatible in any way with
CMAKE_x_COMPILER and should not be used to set it. CMAKE_x_COMPILER is
expected by CMake to be the absolute path to the compiler (and not any
compiler wrapper). The blessed way to use a compiler wrapper with CMake
is to specify it with CMAKE_x_COMPILER_LAUNCHER.
Internally, CMake makes itself compatible with CC and CXX environment
variables by splitting the environment variable and assigning the first
part to CMAKE_x_COMPILER and the rest to the undocumented internal
CMAKE_x_COMPILER_ARG1. Essentially this means treating 'ccache' as the
compiler and 'cmake' as a mandatory first parameter. This mostly works
except for the various places where CMake doesn't actually pass the
mandatory first parameter, like when checking …
=> Remove CMAKE_x_COMPILER from libcxx build.

fuzzing/scripts/custom-build.sh
Currently cc and cxx are hard-wired to 'clang' and 'clang++', however
the user may wish to use another build of clang, like a local build or
something like 'clang-12'. Use CC and CXX when they have 'clang' in
them.
Test the clang version. In order to build llvm-13 libcxx clang version
10 or greater is required. Exit configuration if the detected version is
less than 10.
Output the configured settings for cc and cxx and their versions to
clarify the selected settings.
Fixes: #120
=> Use CC and CXX, check for clang version.

fuzzing/scripts/build/0001-Don-t-override-CC-CFLAGS-and-LDFLAGS.patch, fuzzing/scripts/build/bzip2.sh
The bzip2 build is just a simple Makefile which overrides CC, CFLAGS,
and LDFLAGS. Patch up the Makefile not to do that. Note that the
oss-fuzz bzip2 build does not use the Makefile at all, instead manually
building and linking in the build.sh.
This change allows the i386 oss-fuzz configuration to work.
=> Build bzip2 correctly.

fuzzing/scripts/build/brotli.sh, fuzzing/scripts/build/freetype.sh, fuzzing/scripts/build/glog.sh, fuzzing/scripts/build/libarchive.sh, fuzzing/scripts/build/libcxx.sh, fuzzing/scripts/build/libpng.sh, fuzzing/scripts/build/targets.sh, fuzzing/scripts/build/zlib.sh, fuzzing/scripts/custom-build.sh
Properly quoting in these scripts allows them to run properly even if
there are spaces in the path. Note that while these scripts will work
properly, the actual build does not, since (at least) the zlib install
target will not correctly install to a path with spaces.
=> Quote more strings.

fuzzing/scripts/custom-build.sh
When running cc and cxx to ensure they exist and get their version, do
not quote them as if they were paths but allow them to expand as they
normally would. This allows the compiler to be specified as "ccache
clang" when using ccache or even "clang-11 --driver-mode=g++" when
needing to use a non-default clang++.
=> Unquote cc and cxx when executing.

fuzzing/src/visitors/facevisitor-colrv1.cpp
Fixes stack overflow through recursive PaintGlyph operations,
compare https://gitlab.freedesktop.org/freetype/freetype/-/issues/1159
=> Track VisitedSet at top level before colrv1_start_glyph

fuzzing/src/visitors/facevisitor-charcodes.h
=> Add missing #include to fix C++20 compile error.

fuzzing/src/visitors/glyphvisitor-outlines.cpp
The outline fuzzer was relying on the use of FT_LOAD_NO_BITMAP in "GlyphsOutlinesFuzzTarget()" [0] to produce only glyphs with FT_GLYPH_FORMAT_OUTLINE to satisfy the assert in
"GlyphVisitorOutlines::run" [1].  This was never really true, but with "[truetype] Ingnore FT_LOAD_NO_BITMAP in bitmap-only fonts." [2] this is now very often false.  Because this assert could have been hit already, remove the assert that the glyph has an outline and instead return early if there is no outline.
[0] https://github.com/freetype/freetype2-testing/blob/57d875f1c45b5c9b83bf2e99cedc150108a2b28c/fuzzing/src/targets/glyphs/outlines.cpp#L47
[1] https://github.com/freetype/freetype2-testing/blob/57d875f1c45b5c9b83bf2e99cedc150108a2b28c/fuzzing/src/visitors/glyphvisitor-outlines.cpp#L46
[2] …
=> Check for outlines instead of asserting

fuzzing/src/utils/tarreader.h, fuzzing/src/utils/utils.h
This is for C++ modules build in chromium.
=> Add missing include headers
